apiVersion: apps/v1
kind: Deployment
metadata:
  # Name of the deployment
  name: api-gateway-deployment
  # Labels are key-value pair assigned in this case to the deployment
  # The key can be whatever I want, in this case, I called it app to reference it in the future
  labels:
    # Reffering to api-gateway app
    app: api-gateway
# Specification for the deployment
spec:
  # kubernetes will do whatever it can to ensure having always exactly 1 pod running
  replicas: 1
  selector:
    # This means it will select the pods which its label matches exactly with "app: api-gateway"
    matchLabels:
      app: api-gateway
  template:
    metadata:
      # This indicates the pods created by the deployment will have app: api-gateway as a label
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: registry.cloud.okteto.net/prod-szwtomas/api-gateway:v3
          ports:
            - containerPort: 8181
      # This means that, if the container exits for any reason, it should restart again. It is the default value
      # Other options are OnFailure y Never
      restartPolicy: Always
  